services:
  # A Python web service
  - type: web
    name: crm-system
    env: python
    plan: free # Or choose a paid plan for more resources
    buildCommand: "pip install -r requirements.txt && flask db upgrade"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 # Match the sandbox environment if possible
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV # Set to production for better performance/security
        value: production 
      - key: SECRET_KEY
        generateValue: true # Let Render generate a secure secret key
      - key: DATABASE_URL
        fromDatabase:
          name: crm-database
          property: connectionString

  # A PostgreSQL database
  - type: psql
    name: crm-database
    plan: free # Or choose a paid plan
    databaseName: crm_db
    user: crm_user
    # PostgreSQL version can be specified if needed, e.g.:
    # postgresqlVersion: 14 

